### ISSUE TITLE
DB connection issue authentication fails with right credentials

### ISSUE THREAD

**Issue by chattan** [hgurung/nestjs-boilerplate#1]
error: password authentication failed for user "macmini26"
    at Parser.parseErrorMessage (/Users/macmini26/projects/nestjs-boilerplate/node_modules/pg-protocol/src/parser.ts:369:69)

**Comment by hgurung** [comment]
@chattan There was a coffee rating module that had another database connection which has been removed. Thanks for the feedback.

**Comment by chattan** [comment]
Thanks its working now :)
